set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g status-keys vi
set -g mouse on

set-window-option -g mode-keys vi

set -g status-position top
set -g status-interval 1

set -g status-left-length 100
set -g status-right-length 100

set -g allow-passthrough on
set -g status-justify absolute-centre

set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM


set -g @mode_indicator_empty_mode_style  'bg=#101317,fg=#878787'
set -g @mode_indicator_prefix_mode_style 'bg=#101317,fg=#797EA3'
set -g @mode_indicator_copy_mode_style   'bg=#101317,fg=#9bb4bc'
set -g @mode_indicator_sync_mode_style   'bg=#101317,fg=#C3AD8B'

# Status bar layout
set -g status-bg "#101317"
set -g status-fg "#797EA3"
set -g message-style 'fg=#878787 bg=#101317'
set -g status-right "#[fg=#878787]%a %m/%d/%Y %H:%M"
set -g status-left "#{tmux_mode_indicator}"
setw -g window-status-format "#[fg=#878787,italics]#I:#[italics]#W"
setw -g window-status-current-format "#[fg=#797EA3,italics]#I:#[italics,bold]#{?window_zoomed_flag,#[fg=#b48484](,}#[fg=#ad8dbd,italics,bold]#W#{?window_zoomed_flag,#[fg=#b48484]),}"



# Sets the prefix to Ctrl + A
set -g prefix C-a
bind-key C-a send-prefix

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5
bind S choose-tree -s
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"


bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect' # Never ending persistent sessions
set -g @plugin 'tmux-plugins/tmux-continuum' # Continuous saving + start
set -g @plugin 'MunifTanjim/tmux-mode-indicator'    # Display current tmux mode
set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'

