# Fixing terminal colors
# set-option -sa terminal-overrides ",xterm*:Tc"
# set-option -g default-terminal "tmux-256color"
set -g default-terminal "xterm-kitty"
set -ga terminal-features ',xterm-kitty:RGB'
set -g terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -g terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
set -g mouse on

# starting base window number at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Sets the status bar (and its refresh rate) on top |
set -g status-position top
set -g status-interval 1

set -g status-left "#{tmux_mode_indicator} #{online_status} #{pomodoro_status}"
set -g status-right "CPU:#{cpu_percentage}  #[fg=#ffe291,italics] #(whoami)#[fg=#797ea3]@#[fg=#ffe291]#H "

# Yazi settings
set -g allow-passthrough on
set -g status-justify absolute-centre

set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM


set -g status-bg "#101317"
set -g status-fg "#797ea3"

# plugins 
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect' # Never ending persistent sessions
set -g @plugin 'tmux-plugins/tmux-continuum' # Continuous saving + start
set -g @plugin 'MunifTanjim/tmux-mode-indicator'    # Display current tmux mode
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-online-status'    # Are we connected to the internet?!
# set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'

set -g @online_icon "#[fg=#b4c7a7]"
set -g @offline_icon "#[fg= #ca6d73]"


# Theme - kanagawa
# set -g @plugin 'Nybkox/tmux-kanagawa'
# set -g @kanagawa-show-left-icon session
# set -g @kanagawa-show-empty-plugins false
# set -g @kanagawa-show-location false
# set -g @kanagawa-cpu-display-load false
# set -g @kanagawa-plugins "cpu-usage ram-usage"
# set -g @kanagawa-show-fahrenheit false


# Sets the prefix to Ctrl + A
set -g prefix C-a
bind-key C-a send-prefix

# Sets Prefix + r to source tmux.conf file
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Sets Ctrl + H / V for horizontal / vertical splits in the current working directory
bind-key h split-window -v -c "#{pane_current_path}"
bind-key v split-window -h -c "#{pane_current_path}"

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel



# Set permanent sessions = on
set -g @continuum-restore 'on'

set -g status-left-length 100
set -g status-right-length 100
run '~/.tmux/plugins/tpm/tpm'

