# Fixing terminal colors
# set-option -sa terminal-overrides ",xterm*:Tc"
set-option -g default-terminal "tmux-256color"
set -ga terminal-features ',xterm-kitty:RGB'
set -g terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -g terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
set -g mouse on

# starting base window number at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Sets the status bar (and its refresh rate) on top |
# set -g status-position top
set -g status-interval 1

# plugins 
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect' # Never ending persistent sessions
set -g @plugin 'tmux-plugins/tmux-continuum' # Continuous saving + start

set -g status-justify absolute-centre
set -g monitor-activity on
# set -g @vim_icon "#[fg=$#e5bb7f80]"

set -g @plugin 'rose-pine/tmux' 
set -g @rose_pine_bar_bg_disable 'on'
set -g @rose_pine_bar_bg_disabled_color_option '#101317'
# set -g @plugin 'MunifTanjim/tmux-mode-indicator' # Cool AF mode indicator 

# Rosé Pine theme config
set -g @rose_pine_variant 'main'
set -g @rose_pine_directory 'on'
set -g @rose_pine_show_current_program 'on'
set -g @rose_pine_disable_active_window_menu 'on' # Disables the menu that shows the active window on the left
# set -g @rose_pine_date_time '%H:%M | %a'
# set -g @rose_pine_user 'on'
set -g @rose_pine_username_icon ''
set -g @rose_pine_status_left_prepend_section '#(cat #{socket_path}-\#{session_id}-vimbridge)'
set -g @rose_pine_status_right_append_section '#(cat #{socket_path}-\#{session_id}-vimbridge-R)'
# set -g @rose_pine_bar_bg_transparent_option '7'
# set -g @rose_pine_disable_active_window_menu 'on'
# set -g @rose_pine_default_window_behavior 'on'
# set -g @rose_pine_show_pane_directory 'on'
# set -g @rose_pine_prioritize_windows 'on'
# set -g @rose_pine_width_to_hide '80'
# set -g @rose_pine_window_count '5'
# set -g @rose_pine_user 'on'
# set -g @rose_pine_host 'on'
# set -g @rose_pine_left_separator ' > '
# set -g @rose_pine_right_separator '  '
# set -g @rose_pine_active_window_color 'love'
# set -g @rose_pine_window_status_separator ''
# set -g @rose_pine_window_tabs_enabled 'on' -- OLD

# Sets the prefix to Ctrl + A
set -g prefix C-a
bind-key C-a send-prefix

# Sets Prefix + a to source tmux.conf file
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Sets Ctrl + H / V for horizontal / vertical splits in the current working directory
bind-key h split-window -v -c "#{pane_current_path}"
bind-key v split-window -h -c "#{pane_current_path}"

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Set permanent sessions = on
set -g @continuum-restore 'on'

#set -g status-right '#{tmux-mode-indicator}'

run '~/.tmux/plugins/tpm/tpm'
set -g status-left-length 100
set -g status-right-length 100

